// <auto-generated />
using System;
using DataAccessLayer_FranLink.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DataAccessLayer_FranLink.Migrations
{
    [DbContext(typeof(FranLinkContext))]
    partial class FranLinkContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DataAccessLayer_FranLink.Models.CentralKitchen", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Capacity")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.ToTable("CentralKitchens");
                });

            modelBuilder.Entity("DataAccessLayer_FranLink.Models.Delivery", b =>
                {
                    b.Property<Guid>("DeliveryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DeliveredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeliveryStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("InternalOrderId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("ScheduledDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("DeliveryId");

                    b.HasIndex("InternalOrderId")
                        .IsUnique();

                    b.ToTable("Deliveries");
                });

            modelBuilder.Entity("DataAccessLayer_FranLink.Models.FranchiseStore", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsCentralKitchen")
                        .HasColumnType("boolean");
                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.ToTable("FranchiseStores");
                });

            modelBuilder.Entity("DataAccessLayer_FranLink.Models.InternalOrder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("CentralKitchenId")
                        .HasColumnType("integer");

                    b.Property<int>("FranchiseStoreId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CentralKitchenId");

                    b.HasIndex("FranchiseStoreId");

                    b.HasIndex("UserId");

                    b.ToTable("InternalOrders");
                });

            modelBuilder.Entity("DataAccessLayer_FranLink.Models.InternalOrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("InternalOrderId")
                        .HasColumnType("integer");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("InternalOrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("InternalOrderItems");
                });

            modelBuilder.Entity("DataAccessLayer_FranLink.Models.Inventory", b =>
                {
                    b.Property<Guid>("InventoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BatchNumber")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int?>("CentralKitchenId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("ExpiryDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("FranchiseStoreId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("MaxThreshold")
                        .HasColumnType("integer");

                    b.Property<int>("MinThreshold")
                        .HasColumnType("integer");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.HasKey("InventoryId");

                    b.HasIndex("CentralKitchenId");

                    b.HasIndex("FranchiseStoreId");

                    b.HasIndex("ProductId");

                    b.ToTable("Inventories");
                });

            modelBuilder.Entity("DataAccessLayer_FranLink.Models.InventoryDisposal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<Guid?>("ApprovedByUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ApprovedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DisposalDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DisposedByUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("InventoryId")
                        .HasColumnType("uuid");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("ApprovedByUserId");

                    b.HasIndex("DisposedByUserId");

                    b.HasIndex("InventoryId");

                    b.ToTable("InventoryDisposals");
                });

            modelBuilder.Entity("DataAccessLayer_FranLink.Models.InventoryTransfer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<Guid?>("ApprovedByUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ApprovedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("CompletedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("FromCentralKitchenId")
                        .HasColumnType("integer");

                    b.Property<int?>("FromStoreId")
                        .HasColumnType("integer");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<DateTime>("RequestDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("RequestedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int?>("ToCentralKitchenId")
                        .HasColumnType("integer");

                    b.Property<int?>("ToStoreId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ApprovedByUserId");

                    b.HasIndex("FromCentralKitchenId");

                    b.HasIndex("FromStoreId");

                    b.HasIndex("ProductId");

                    b.HasIndex("RequestedByUserId");

                    b.HasIndex("ToCentralKitchenId");

                    b.HasIndex("ToStoreId");

                    b.ToTable("InventoryTransfers");
                });

            modelBuilder.Entity("DataAccessLayer_FranLink.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<string>("SKU")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Unit")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("DataAccessLayer_FranLink.Models.ProductionRecord", b =>
                {
                    b.Property<int>("ProductionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ProductionId"));

                    b.Property<int>("ActualQuantity")
                        .HasColumnType("integer");

                    b.Property<int>("CentralKitchenId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("PlannedQuantity")
                        .HasColumnType("integer");

                    b.Property<Guid>("ProducedByUserId")
                        .HasColumnType("uuid");

                    b.Property<int>("RecipeId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("ProductionId");

                    b.HasIndex("CentralKitchenId");

                    b.HasIndex("ProducedByUserId");

                    b.HasIndex("RecipeId");

                    b.ToTable("ProductionRecords");
                });

            modelBuilder.Entity("DataAccessLayer_FranLink.Models.QualityFeedback", b =>
                {
                    b.Property<Guid>("QualityFeedbackId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer");

                    b.Property<int>("Rating")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("QualityFeedbackId");

                    b.HasIndex("ProductId");

                    b.HasIndex("UserId");

                    b.ToTable("QualityFeedbacks");
                });

            modelBuilder.Entity("DataAccessLayer_FranLink.Models.Recipe", b =>
                {
                    b.Property<int>("RecipeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RecipeId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("EstimatedTime")
                        .HasColumnType("numeric");

                    b.Property<string>("Instructions")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("OutputQuantity")
                        .HasColumnType("integer");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("RecipeId");

                    b.HasIndex("ProductId");

                    b.ToTable("Recipes");
                });

            modelBuilder.Entity("DataAccessLayer_FranLink.Models.RecipeItem", b =>
                {
                    b.Property<int>("RecipeItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RecipeItemId"));

                    b.Property<int>("IngredientProductId")
                        .HasColumnType("integer");

                    b.Property<string>("Notes")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("numeric");

                    b.Property<int>("RecipeId")
                        .HasColumnType("integer");

                    b.Property<string>("Unit")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("RecipeItemId");

                    b.HasIndex("IngredientProductId");

                    b.HasIndex("RecipeId");

                    b.ToTable("RecipeItems");
                });

            modelBuilder.Entity("DataAccessLayer_FranLink.Models.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RoleId"));

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("RoleId");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("DataAccessLayer_FranLink.Models.SystemConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ConfigKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ConfigValue")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ConfigKey")
                        .IsUnique();

                    b.ToTable("SystemConfigs");
                });

            modelBuilder.Entity("DataAccessLayer_FranLink.Models.User", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("FranchiseStoreId")
                        .HasColumnType("integer");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("UserId");

                    b.HasIndex("FranchiseStoreId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("DataAccessLayer_FranLink.Models.UserRole", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles");
                });

            modelBuilder.Entity("DataAccessLayer_FranLink.Models.Delivery", b =>
                {
                    b.HasOne("DataAccessLayer_FranLink.Models.InternalOrder", "InternalOrder")
                        .WithOne("Delivery")
                        .HasForeignKey("DataAccessLayer_FranLink.Models.Delivery", "InternalOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InternalOrder");
                });

            modelBuilder.Entity("DataAccessLayer_FranLink.Models.InternalOrder", b =>
                {
                    b.HasOne("DataAccessLayer_FranLink.Models.CentralKitchen", "CentralKitchen")
                        .WithMany()
                        .HasForeignKey("CentralKitchenId");

                    b.HasOne("DataAccessLayer_FranLink.Models.FranchiseStore", "FranchiseStore")
                        .WithMany("InternalOrders")
                        .HasForeignKey("FranchiseStoreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataAccessLayer_FranLink.Models.User", "User")
                        .WithMany("InternalOrders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CentralKitchen");

                    b.Navigation("FranchiseStore");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DataAccessLayer_FranLink.Models.InternalOrderItem", b =>
                {
                    b.HasOne("DataAccessLayer_FranLink.Models.InternalOrder", "InternalOrder")
                        .WithMany("Items")
                        .HasForeignKey("InternalOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataAccessLayer_FranLink.Models.Product", "Product")
                        .WithMany("InternalOrderItems")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InternalOrder");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("DataAccessLayer_FranLink.Models.Inventory", b =>
                {
                    b.HasOne("DataAccessLayer_FranLink.Models.CentralKitchen", "CentralKitchen")
                        .WithMany("Inventories")
                        .HasForeignKey("CentralKitchenId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DataAccessLayer_FranLink.Models.FranchiseStore", "FranchiseStore")
                        .WithMany("Inventories")
                        .HasForeignKey("FranchiseStoreId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DataAccessLayer_FranLink.Models.Product", "Product")
                        .WithMany("Inventories")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CentralKitchen");

                    b.Navigation("FranchiseStore");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("DataAccessLayer_FranLink.Models.InventoryDisposal", b =>
                {
                    b.HasOne("DataAccessLayer_FranLink.Models.User", "ApprovedBy")
                        .WithMany("ApprovedDisposals")
                        .HasForeignKey("ApprovedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DataAccessLayer_FranLink.Models.User", "DisposedBy")
                        .WithMany("RequestedDisposals")
                        .HasForeignKey("DisposedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DataAccessLayer_FranLink.Models.Inventory", "Inventory")
                        .WithMany()
                        .HasForeignKey("InventoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApprovedBy");

                    b.Navigation("DisposedBy");

                    b.Navigation("Inventory");
                });

            modelBuilder.Entity("DataAccessLayer_FranLink.Models.InventoryTransfer", b =>
                {
                    b.HasOne("DataAccessLayer_FranLink.Models.User", "ApprovedBy")
                        .WithMany("ApprovedTransfers")
                        .HasForeignKey("ApprovedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DataAccessLayer_FranLink.Models.CentralKitchen", "FromCentralKitchen")
                        .WithMany()
                        .HasForeignKey("FromCentralKitchenId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DataAccessLayer_FranLink.Models.FranchiseStore", "FromStore")
                        .WithMany()
                        .HasForeignKey("FromStoreId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DataAccessLayer_FranLink.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataAccessLayer_FranLink.Models.User", "RequestedBy")
                        .WithMany("RequestedTransfers")
                        .HasForeignKey("RequestedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DataAccessLayer_FranLink.Models.CentralKitchen", "ToCentralKitchen")
                        .WithMany()
                        .HasForeignKey("ToCentralKitchenId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DataAccessLayer_FranLink.Models.FranchiseStore", "ToStore")
                        .WithMany()
                        .HasForeignKey("ToStoreId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ApprovedBy");

                    b.Navigation("FromCentralKitchen");

                    b.Navigation("FromStore");

                    b.Navigation("Product");

                    b.Navigation("RequestedBy");

                    b.Navigation("ToCentralKitchen");

                    b.Navigation("ToStore");
                });

            modelBuilder.Entity("DataAccessLayer_FranLink.Models.ProductionRecord", b =>
                {
                    b.HasOne("DataAccessLayer_FranLink.Models.CentralKitchen", "CentralKitchen")
                        .WithMany()
                        .HasForeignKey("CentralKitchenId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DataAccessLayer_FranLink.Models.User", "ProducedByUser")
                        .WithMany()
                        .HasForeignKey("ProducedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DataAccessLayer_FranLink.Models.Recipe", "Recipe")
                        .WithMany()
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CentralKitchen");

                    b.Navigation("ProducedByUser");

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("DataAccessLayer_FranLink.Models.QualityFeedback", b =>
                {
                    b.HasOne("DataAccessLayer_FranLink.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataAccessLayer_FranLink.Models.User", "User")
                        .WithMany("QualityFeedbacks")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("User");
                });
            modelBuilder.Entity("DataAccessLayer_FranLink.Models.Recipe", b =>
                {
                    b.HasOne("DataAccessLayer_FranLink.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("DataAccessLayer_FranLink.Models.RecipeItem", b =>
                {
                    b.HasOne("DataAccessLayer_FranLink.Models.Product", "IngredientProduct")
                        .WithMany("RecipeItems")
                        .HasForeignKey("IngredientProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DataAccessLayer_FranLink.Models.Recipe", "Recipe")
                        .WithMany("RecipeItems")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IngredientProduct");

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("DataAccessLayer_FranLink.Models.User", b =>
                {
                    b.HasOne("DataAccessLayer_FranLink.Models.FranchiseStore", "FranchiseStore")
                        .WithMany("Users")
                        .HasForeignKey("FranchiseStoreId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("FranchiseStore");
                });

            modelBuilder.Entity("DataAccessLayer_FranLink.Models.UserRole", b =>
                {
                    b.HasOne("DataAccessLayer_FranLink.Models.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataAccessLayer_FranLink.Models.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DataAccessLayer_FranLink.Models.CentralKitchen", b =>
                {
                    b.Navigation("Inventories");
                });

            modelBuilder.Entity("DataAccessLayer_FranLink.Models.FranchiseStore", b =>
                {
                    b.Navigation("InternalOrders");

                    b.Navigation("Inventories");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("DataAccessLayer_FranLink.Models.InternalOrder", b =>
                {
                    b.Navigation("Delivery")
                        .IsRequired();

                    b.Navigation("Items");
                });

            modelBuilder.Entity("DataAccessLayer_FranLink.Models.Product", b =>
                {
                    b.Navigation("InternalOrderItems");

                    b.Navigation("Inventories");

                    b.Navigation("RecipeItems");
                });

            modelBuilder.Entity("DataAccessLayer_FranLink.Models.Recipe", b =>
                {
                    b.Navigation("RecipeItems");
                });

            modelBuilder.Entity("DataAccessLayer_FranLink.Models.Role", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("DataAccessLayer_FranLink.Models.User", b =>
                {
                    b.Navigation("ApprovedDisposals");

                    b.Navigation("ApprovedTransfers");

                    b.Navigation("InternalOrders");

                    b.Navigation("QualityFeedbacks");

                    b.Navigation("RequestedDisposals");

                    b.Navigation("RequestedTransfers");

                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
